# -*- coding: utf-8 -*-
"""Exp12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1X6TxlpFRnzMUAxne1JxXjubTrik5GRCf
"""

Q12="""12.Spreadsheet Operations: Demonstrate python program to read the data from the
spreadsheet and write the data in to the spreadsheet"""
print(Q12)

import openpyxl
# Writing Data
# Create a new workbook
wb = openpyxl.Workbook()
sheet = wb.active
sheet.title = "EmployeeData"
# Write data into cells
sheet['A1'] = "Name"
sheet['B1'] = "Department"
sheet['C1'] = "Salary"
sheet.append(["sasi", "HR", 30000])
sheet.append(["ravi", "IT", 40000])
sheet.append(["anil", "Finance", 35000])
# Save the workbook
wb.save("employee_data.xlsx")
print("Data written successfully to 'employee_data.xlsx'.")
# ---------- Reading Data ----------
# Load the existing workbook
wb2 = openpyxl.load_workbook("employee_data.xlsx")
sheet2 = wb2.active
print("\nReading data from 'employee_data.xlsx':")
for row in sheet2.iter_rows(values_only=True):
    print(row)

"""Result : the program is executed successfully"""