# -*- coding: utf-8 -*-
"""Exp2b.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1u-qqNi4GrJMSJ0SEUJYGfMpPcp2orL0Q
"""

Q2b="2.develop a python program to check whether a given number is palindrome or not and also count the no.of occcurances of each digit in the input number "
print(Q2b)

input_str = input("Enter a string: ")
if input_str == input_str[::-1]:
    print("Palindrome")
else:
    print("Not Palindrome")

for ch in set(input_str):
    count = input_str.count(ch)
    print(f"'{ch}' appears {count} times")

"""Result:the program is executed successfully

"""